### ISSUE TITLE
Unknown affixes displayed

### ISSUE THREAD

**Issue by LinkLenain** [WFrancois/wow-affixes#2]
Hi,

First, thanks for this great website! It is very useful to know in advance what will be the next affixes.

A small issue I would like to raise: there is an "Unknown" week in the calendar --> Maybe next Wednesday the content of the following could be improved (as it will point on this specific week) :
https://github.com/WFrancois/wow-affixes/blob/517a5f8cc139ccfc6da2ea9e97aa1ce66571fdae/src/Service/WowWeek.php#L14

Thanks in advance for the next update and best regards,
Link

**Comment by LinkLenain** [comment]
In fact, it looks like some rotation are missing: According to [wowhead](https://www.wowhead.com/mythic-keystones-and-dungeons-guide) (see Affix Rotation), there are 12 cycles whereas your list only contains 10 of them (if we include the Unknown description)

I hope it will help to enhance the website :)

**Comment by WFrancois** [comment]
Hi !

This `Unknown` comes from the 8.2 where Blizzard changed the affix rotation (so we need to see the full rotation).

Though if the wowhead rotation is true, I should be able to update everything ! We'll see later in the day the affix of this week :) 

I'll update accordingly the website (and I'll need to think about adding the beguiling type as well :) )

Thanks for bringing this up to me ! :) 

Isak.

**Comment by LinkLenain** [comment]
Well, beguiling is the new S3 affix which came with the 8.2. In fact, there is 3 kind of beguiling. Depending of the week, there is more void / tide / enchanted emissary (this is also specified in the affix rotation).
Maybe this could be another improvement rather than being a fix for the current issue ;)

**Comment by WFrancois** [comment]
Hey !

Just added the beguiling type with the latest commit :) https://github.com/WFrancois/wow-affixes/commit/8fbe4c0b5979939ccc04810c7122741c5425c0cc

Isak.

**Comment by LinkLenain** [comment]
Hey,

Nice, thanks a lot !
