### ISSUE TITLE
Swap language doesn't work

### ISSUE THREAD

**Issue by diegocolero** [WFrancois/wow-affixes#51]
Hi, 
When I try to swap language page reload and doesn't change.
If you need help with translations, I may help you with spanish.

**Comment by WFrancois** [comment]
Hey!

Thanks for the report, indeed it looks like there's an issue where it doesn't change the language properly, I need to look into it! :(

**Comment by WFrancois** [comment]
Hey @diegocolero !

I've just fixed the translations system, so now at least it should correctly translate.
It works fully in French. For other language, it only translate the affix name (as wowhead is linking to the correct translated page).

If you want, feel free to translate and open a pull request on https://github.com/WFrancois/wow-affixes/blob/master/translations/messages.es.yaml (you can see how it was done in https://github.com/WFrancois/wow-affixes/blob/master/translations/messages.en.yaml for example)

**Comment by diegocolero** [comment]
Hey!

Thank you for response, I'll try do a pull request for spanish translate. 

Have a nice day
